export const initialCourses = [
    {
        id: 1,
        title: "100 Days of Code: The Complete Python Pro Bootcamp",
        description: "Master Python with 100 projects in 100 days",
        instructor: "Angela Yu",
        price: "$38.69",
        duration: "55h 21m",
        category: "Python",
        rating: 4.7,
        isBestseller: true,
        thumbnail: "assets/images/card_image/udemy_course.jpg"
    },
    {
        id: 2,
        title: "Machine Learning A-Z: AI, Python & R + ChatGPT Prize [2025]",
        description: "Learn Machine Learning using Python & R",
        instructor: "Kirill Eremenko",
        price: "$36.29",
        duration: "42h 44m",
        category: "Python",
        rating: 4.5,
        isBestseller: true,
        thumbnail: "assets/images/card_image/encrypted.jpeg"
    },
    {
        id: 3,
        title: "The Complete JavaScript Course 2025: From Zero to Expert!",
        description: "Master modern JavaScript from the beginning",
        instructor: "Jonas Schmedtmann",
        price: "$42.99",
        duration: "68h 15m",
        category: "JavaScript",
        rating: 4.8,
        isBestseller: true,
        thumbnail: "assets/images/card_image/javascript_code.jpg"
    },
    {
        id: 4,
        title: "Java Programming Masterclass for Software Developers",
        description: "Learn Java Programming from a professional developer",
        instructor: "Tim Buchalka",
        price: "$34.50",
        duration: "80h 10m",
        category: "Java",
        rating: 4.6,
        isBestseller: false,
        thumbnail: "assets/images/card_image/reactjs_code.jpg"
    },
    {
        id: 5,
        title: "Data Science and Machine Learning Bootcamp with R",
        description: "Learn Data Science with R Programming",
        instructor: "Jose Portilla",
        price: "$39.99",
        duration: "58h 30m",
        category: "R",
        rating: 4.7,
        isBestseller: true,
        thumbnail: "assets/images/card_image/R.jpg"
    },
    {
        id: 6,
        title: "The Complete Web Developer Bootcamp 2025",
        description: "Become a full-stack web developer",
        instructor: "Colt Steele",
        price: "$49.99",
        duration: "56h 20m",
        category: "Web Development",
        rating: 4.9,
        isBestseller: true,
        thumbnail: "assets/images/card_image/web_bootcamp.jpeg"
    },
    {
        id: 7,
        title: "Complete SQL Bootcamp 2025: Go from Zero to Hero",
        description: "Master SQL for database management",
        instructor: "Jose Portilla",
        price: "$34.99",
        duration: "41h 15m",
        category: "SQL",
        rating: 4.8,
        isBestseller: true,
        thumbnail: "assets/images/card_image/sql_bootcamp.jpeg"
    },
    {
        id: 8,
        title: "The Complete iOS App Development Bootcamp 2025",
        description: "Become an iOS developer",
        instructor: "Angela Yu",
        price: "$45.99",
        duration: "75h 5m",
        category: "iOS Development",
        rating: 4.7,
        isBestseller: true,
        thumbnail: "assets/images/card_image/ios_development.jpeg"
    },
    {
        id: 9,
        title: "The Complete MERN Stack Developer Course 2025",
        description: "Build full-stack web applications",
        instructor: "Andrei Neagoie",
        price: "$38.79",
        duration: "70h 35m",
        category: "MERN Stack",
        rating: 4.6,
        isBestseller: true,
        thumbnail: "assets/images/card_image/stack_dev.jpeg"
    },
    {
        id: 10,
        title: "React Native - The Practical Guide [2025 Edition]",
        description: "Build native mobile apps with React Native",
        instructor: "Maximilian Schwarzmüller",
        price: "$44.99",
        duration: "50h 5m",
        category: "React Native",
        rating: 4.8,
        isBestseller: true,
        thumbnail: "assets/images/card_image/react_guide.jpeg"
    },
    {
        id: 11,
        title: "Python for Data Science and Machine Learning Bootcamp",
        description: "Complete guide to using Python for Data Science",
        instructor: "Jose Portilla",
        price: "$39.99",
        duration: "65h 10m",
        category: "Python",
        rating: 4.7,
        isBestseller: true,
        thumbnail: "assets/images/card_image/python_data_science.jpeg"
    },
    {
        id: 12,
        title: "Complete React Developer in 2025 (w/ Redux, Hooks, GraphQL)",
        description: "Master React and Redux development",
        instructor: "Andrei Neagoie",
        price: "$48.49",
        duration: "61h 40m",
        category: "React.js",
        rating: 4.9,
        isBestseller: true,
        thumbnail: "assets/images/card_image/complete_react.jpeg"
    },
    {
        id: 13,
        title: "Web Development Bootcamp with HTML, CSS, JavaScript",
        description: "Complete web development bootcamp",
        instructor: "Colt Steele",
        price: "$42.79",
        duration: "63h 55m",
        category: "Web Development",
        rating: 4.8,
        isBestseller: true,
        thumbnail: "assets/images/card_image/web_dev_bootcamp.jpeg"
    },
    {
        id: 14,
        title: "Flutter & Dart - The Complete Guide [2025 Edition]",
        description: "Master Flutter development",
        instructor: "Maximilian Schwarzmüller",
        price: "$44.99",
        duration: "52h 30m",
        category: "Flutter",
        rating: 4.9,
        isBestseller: true,
        thumbnail: "assets/images/card_image/complete_flutter.jpeg"
    },
    {
        id: 15,
        title: "Go: The Complete Guide for Beginners",
        description: "Learn Go programming language",
        instructor: "Stephen Grider",
        price: "$35.99",
        duration: "45h 10m",
        category: "Go",
        rating: 4.7,
        isBestseller: false,
        thumbnail: "assets/images/card_image/complete_guide.jpeg"
    },
    {
        id: 16,
        title: "Complete C++ Developer Course: From Beginner to Expert",
        description: "Master C++ programming",
        instructor: "Tim Buchalka",
        price: "$49.99",
        duration: "78h 45m",
        category: "C++",
        rating: 4.8,
        isBestseller: true,
        thumbnail: "assets/images/card_image/complete_c++.jpeg"
    },
    {
        id: 17,
        title: "Introduction to Machine Learning with Python",
        description: "Learn machine learning with Python",
        instructor: "Andreas Müller",
        price: "$42.99",
        duration: "60h 20m",
        category: "Python",
        rating: 4.8,
        isBestseller: true,
        thumbnail: "assets/images/card_image/ml_python.jpeg"
    },
    {
        id: 18,
        title: "Mastering Data Science with Python & SQL",
        description: "Complete data science course",
        instructor: "Sundas Khalid",
        price: "$40.99",
        duration: "62h 10m",
        category: "Data Science",
        rating: 4.7,
        isBestseller: false,
        thumbnail: "assets/images/card_image/master_python_sql.jpeg"
    },
    {
        id: 19,
        title: "React JS & Redux Masterclass (2025 Edition)",
        description: "Master React and Redux",
        instructor: "Stephen Grider",
        price: "$49.99",
        duration: "58h 50m",
        category: "React.js",
        rating: 4.9,
        isBestseller: true,
        thumbnail: "assets/images/card_image/react_redux.jpeg"
    },
    {
        id: 20,
        title: "Mastering Android Development with Kotlin",
        description: "Learn Android development",
        instructor: "Morteza Kordi",
        price: "$46.50",
        duration: "72h 30m",
        category: "Kotlin",
        rating: 4.7,
        isBestseller: true,
        thumbnail: "assets/images/card_image/kotlin_android.jpeg"
    },
    {
        id: 21,
        title: "R Programming A-Z™: R For Data Science With Real Exercises!",
        description: "Learn R programming for data science",
        instructor: "Kirill Eremenko",
        price: "$29.99",
        duration: "10h 33m",
        category: "R",
        rating: 4.6,
        isBestseller: true,
        thumbnail: "assets/images/card_image/python.jpg"
    },
    {
        id: 22,
        title: "Learn C# Programming (In Ten Easy Steps)",
        description: "Master C# programming fundamentals",
        instructor: "Huw Collingbourne",
        price: "$29.99",
        duration: "13h 30m",
        category: "C#",
        rating: 4.6,
        isBestseller: false,
        thumbnail: "assets/images/card_image/python_2.jpg"
    },
    {
        id: 23,
        title: "PHP for Beginners - Become a PHP Master - CMS Project",
        description: "Learn PHP from scratch to advanced",
        instructor: "Edwin Diaz",
        price: "$34.99",
        duration: "38h 0m",
        category: "PHP",
        rating: 4.5,
        isBestseller: true,
        thumbnail: "assets/images/card_image/php.jpeg"
    },
    {
        id: 24,
        title: "Swift 5 iOS Application Developer Bootcamp",
        description: "Become an iOS developer with Swift",
        instructor: "Nick Walter",
        price: "$39.99",
        duration: "60h 0m",
        category: "Swift",
        rating: 4.7,
        isBestseller: true,
        thumbnail: "assets/images/card_image/ztm_swift.jpg"
    },
    {
        id: 25,
        title: "Kotlin for Android Development: Beginner to Advanced",
        description: "Master Kotlin for Android development",
        instructor: "Morteza Kordi",
        price: "$36.99",
        duration: "40h 0m",
        category: "Kotlin",
        rating: 4.6,
        isBestseller: true,
        thumbnail: "assets/images/card_image/flutter.jpg"
    },
    {
        id: 26,
        title: "Dart and Flutter: The Complete Developer's Guide",
        description: "Master Dart and Flutter development",
        instructor: "Stephen Grider",
        price: "$42.99",
        duration: "55h 0m",
        category: "Dart",
        rating: 4.8,
        isBestseller: true,
        thumbnail: "assets/images/card_image/flutter_guide.jpeg"
    },
    {
        id: 27,
        title: "TypeScript: The Complete Developer's Guide",
        description: "Learn TypeScript from ground up",
        instructor: "Stephen Grider",
        price: "$29.99",
        duration: "30h 0m",
        category: "TypeScript",
        rating: 4.7,
        isBestseller: false,
        thumbnail: "assets/images/card_image/typescript.jpg"
    },
    {
        id: 28,
        title: "Go: The Complete Developer's Guide",
        description: "Master Go programming language",
        instructor: "Todd McLeod",
        price: "$35.99",
        duration: "45h 0m",
        category: "Go",
        rating: 4.6,
        isBestseller: false,
        thumbnail: "assets/images/card_image/go.jpg"
    },
    {
        id: 29,
        title: "SQL for Data Analysis: Beginner to Advanced",
        description: "Master SQL for data analysis",
        instructor: "Maven Analytics",
        price: "$32.99",
        duration: "20h 0m",
        category: "SQL",
        rating: 4.7,
        isBestseller: true,
        thumbnail: "assets/images/card_image/sql.jpg"
    },
    {
        id: 30,
        title: "HTML and CSS: Build Responsive Websites",
        description: "Learn modern HTML and CSS",
        instructor: "Jonas Schmedtmann",
        price: "$37.99",
        duration: "25h 0m",
        category: "HTML",
        rating: 4.8,
        isBestseller: true,
        thumbnail: "assets/images/card_image/html.jpg"
    },
    {
        id: 31,
        title: "CSS: The Complete Guide (2025 Edition)",
        description: "Master modern CSS techniques",
        instructor: "Maximilian Schwarzmüller",
        price: "$34.99",
        duration: "30h 0m",
        category: "CSS",
        rating: 4.7,
        isBestseller: true,
        thumbnail: "assets/images/card_image/css_guide.jpeg"
    },
    {
        id: 32,
        title: "Python for Beginners - Learn Python Programming from Scratch",
        description: "Start your Python journey",
        instructor: "Jose Portilla",
        price: "$29.99",
        duration: "30h 0m",
        category: "Python",
        rating: 4.7,
        isBestseller: true,
        thumbnail: "assets/images/card_image/python_beginner.jpeg"
    },
    {
        id: 33,
        title: "Java Programming Masterclass - Beginner to Advanced",
        description: "Complete Java programming guide",
        instructor: "Tim Buchalka",
        price: "$39.99",
        duration: "40h 0m",
        category: "Java",
        rating: 4.6,
        isBestseller: true,
        thumbnail: "assets/images/card_image/java_beginner.jpeg"
    },
    {
        id: 34,
        title: "The Complete JavaScript Course - From Beginner to Expert",
        description: "Master JavaScript development",
        instructor: "Jonas Schmedtmann",
        price: "$44.99",
        duration: "45h 0m",
        category: "JavaScript",
        rating: 4.8,
        isBestseller: true,
        thumbnail: "assets/images/card_image/js_beginner.jpeg"
    },
    {
        id: 35,
        title: "C++ Programming for Beginners - Master C++ from Scratch",
        description: "Learn C++ programming basics",
        instructor: "Frank Mitropoulos",
        price: "$24.99",
        duration: "35h 0m",
        category: "C++",
        rating: 4.5,
        isBestseller: false,
        thumbnail: "assets/images/card_image/c++_beginner.jpeg"
    },
    {
        id: 36,
        title: "C# for Beginners - Learn C# Programming with Real-World Projects",
        description: "Start your C# journey",
        instructor: "Mosh Hamedani",
        price: "$19.99",
        duration: "25h 0m",
        category: "C#",
        rating: 4.4,
        isBestseller: false,
        thumbnail: "assets/images/card_image/c#_beginner.jpeg"
    },
    {
        id: 37,
        title: "PHP for Beginners - Become a PHP Master - CMS Project",
        description: "Learn PHP development",
        instructor: "Edwin Diaz",
        price: "$34.99",
        duration: "38h 0m",
        category: "PHP",
        rating: 4.5,
        isBestseller: true,
        thumbnail: "assets/images/card_image/php_beginner.jpeg"
    },
    {
        id: 38,
        title: "Swift Programming for Beginners - Build iOS Apps",
        description: "Start iOS development with Swift",
        instructor: "Angela Yu",
        price: "$29.99",
        duration: "28h 0m",
        category: "Swift",
        rating: 4.6,
        isBestseller: true,
        thumbnail: "assets/images/card_image/swift_beginner.jpeg"
    },
    {
        id: 39,
        title: "Kotlin for Beginners - Learn Kotlin Programming for Android Development",
        description: "Start Android development with Kotlin",
        instructor: "Morteza Kordi",
        price: "$32.99",
        duration: "27h 0m",
        category: "Kotlin",
        rating: 4.7,
        isBestseller: false,
        thumbnail: "assets/images/card_image/kotlin_beginner.jpeg"
    },
    {
        id: 40,
        title: "Dart for Beginners - Master Dart for Flutter Development",
        description: "Learn Dart programming",
        instructor: "Andrea Bizzotto",
        price: "$29.99",
        duration: "24h 0m",
        category: "Dart",
        rating: 4.6,
        isBestseller: true,
        thumbnail: "assets/images/card_image/flutter_beginner.jpeg"
    },
    {
        id: 41,
        title: "TypeScript for Beginners - Learn TypeScript Programming",
        description: "Start TypeScript development",
        instructor: "Maximilian Schwarzmüller",
        price: "$19.99",
        duration: "18h 0m",
        category: "TypeScript",
        rating: 4.5,
        isBestseller: false,
        thumbnail: "assets/images/card_image/ts_beginner.jpeg"
    }
];